# Copyright (c) 2026 Ampere Computing. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
#
# Assisted and/or generated by Codex:GPT-5

import os
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory

from catscan.argument_parser import ArgumentParser


class TestArgumentParserConfigDir(unittest.TestCase):
    def parser(self, config_dir: str) -> ArgumentParser:
        parser = ArgumentParser(arg_file_path=[config_dir])
        parser.add_argument("input", nargs="?")
        parser.add_argument("--cache")
        parser.add_argument("--child")
        parser.add_argument("--log")
        parser.add_argument("--parent")
        return parser

    def write_config(self, path: Path, content: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    def test_config_dir_expands_in_positional_argument(self):
        with TemporaryDirectory() as config_dir:
            self.write_config(Path(config_dir, "top.cfg"), "%config_dir%/events.es\n")

            args = self.parser(config_dir).parse_args(["@top.cfg"])

            self.assertEqual(args.input, os.path.realpath(os.path.join(config_dir, "events.es")))

    def test_config_dir_expands_in_option_values(self):
        with TemporaryDirectory() as config_dir:
            self.write_config(
                Path(config_dir, "top.cfg"),
                "--log %config_dir%/catscan.log\n--cache=%config_dir%/cache.pkl\n",
            )

            args = self.parser(config_dir).parse_args(["@top.cfg"])

            self.assertEqual(args.log, os.path.realpath(os.path.join(config_dir, "catscan.log")))
            self.assertEqual(args.cache, os.path.realpath(os.path.join(config_dir, "cache.pkl")))

    def test_config_dir_updates_for_nested_config_files(self):
        with TemporaryDirectory() as config_dir:
            nested_dir = Path(config_dir, "nested")
            self.write_config(
                Path(config_dir, "top.cfg"),
                "@nested/child.cfg\n--parent %config_dir%/parent.log\n",
            )
            self.write_config(nested_dir / "child.cfg", "--child %config_dir%/child.log\n")

            args = self.parser(config_dir).parse_args(["@top.cfg"])

            self.assertEqual(args.child, os.path.realpath(nested_dir / "child.log"))
            self.assertEqual(args.parent, os.path.realpath(os.path.join(config_dir, "parent.log")))

    def test_config_dir_is_not_expanded_for_command_line_arguments(self):
        with TemporaryDirectory() as config_dir:
            args = self.parser(config_dir).parse_args(["%config_dir%/events.es"])

            self.assertEqual(args.input, "%config_dir%/events.es")


if __name__ == "__main__":
    unittest.main()
