# Copyright (c) 2024 Ampere Computing. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause

import re
from collections.abc import Callable, Sequence
from typing import Any

import urwid
from perf_streams.event_stream import Event

from catscan.data import EventStreamData, summary_histogram
from catscan.state import CatscanState, HoverSelection
from catscan.util import str_fit_width, str_width


class _HoverPopupBody(urwid.widget.Widget):
    """Text body for a hover popup."""

    _sizing = frozenset(["box"])
    _selectable = False
    LABEL_ATTR = "hover_popup_label"

    def __init__(self, lines: Sequence[str], bold_labels: bool = False) -> None:
        self.lines = list(lines)
        self.bold_labels = bold_labels
        super().__init__()

    def _row_attrs(self, line: str, inner_width: int) -> tuple[bytes, list[tuple[str | None, int]]]:
        fitted = str_fit_width(line, inner_width)
        padding = " " * (inner_width - str_width(fitted))
        row = fitted + padding

        if not self.bold_labels or ":" not in fitted:
            return row.encode(), [(None, len(row.encode()))]

        label_end = fitted.index(":") + 1
        return row.encode(), [
            (self.LABEL_ATTR, len(fitted[:label_end].encode())),
            (None, len((fitted[label_end:] + padding).encode())),
        ]

    def render(
        self,
        size: tuple[()] | tuple[int] | tuple[int, int],
        focus: bool = False,
    ) -> urwid.canvas.Canvas:
        maxcol, maxrow = size
        if maxcol <= 0 or maxrow <= 0:
            return urwid.canvas.TextCanvas([(" " * maxcol).encode()] * maxrow)

        rows = []
        attrs = []
        for line in self.lines[:maxrow]:
            row, row_attrs = self._row_attrs(line, maxcol)
            rows.append(row)
            attrs.append(row_attrs)

        while len(rows) < maxrow:
            row = (" " * maxcol).encode()
            rows.append(row)
            attrs.append([(None, len(row))])

        return urwid.canvas.TextCanvas(rows, attrs)


class HoverPopup(urwid.WidgetWrap):
    """Small hover popup rendered as a boxed text canvas."""

    _selectable = False
    MAX_WIDTH = 72
    MAX_HEIGHT = 16

    def __init__(self, lines: Sequence[str], bold_labels: bool = False) -> None:
        self.lines = list(lines)
        self.bold_labels = bold_labels
        symbols = urwid.LineBox.Symbols.LIGHT
        body = _HoverPopupBody(self.lines, bold_labels)
        super().__init__(
            urwid.LineBox(
                body,
                tlcorner=symbols.TOP_LEFT_ROUNDED,
                trcorner=symbols.TOP_RIGHT_ROUNDED,
                blcorner=symbols.BOTTOM_LEFT_ROUNDED,
                brcorner=symbols.BOTTOM_RIGHT_ROUNDED,
            )
        )

    @property
    def desired_width(self) -> int:
        content_width = max([str_width(line) for line in self.lines] or [0])
        return max(4, min(content_width + 2, self.MAX_WIDTH))

    @property
    def desired_height(self) -> int:
        return max(3, min(len(self.lines) + 2, self.MAX_HEIGHT))

    def render(
        self,
        size: tuple[()] | tuple[int] | tuple[int, int],
        focus: bool = False,
    ) -> urwid.canvas.Canvas:
        maxcol, maxrow = size
        if maxcol < 2 or maxrow < 2:
            return urwid.canvas.TextCanvas([(" " * maxcol).encode()] * maxrow)
        return super().render(size, focus)


# Assisted and/or generated by Codex:gpt-5
class HoverPopupController:
    """Manage hover popup target state, content, and rendering."""

    def __init__(
        self,
        state: CatscanState,
        stream_data: EventStreamData,
        hexargs_re: re.Pattern,
        get_sidebar_width: Callable[[], int],
        invalidate: Callable[[], None],
    ) -> None:
        self.state = state
        self.stream_data = stream_data
        self.hexargs_re = hexargs_re
        self.get_sidebar_width = get_sidebar_width
        self.invalidate = invalidate

        self.target = HoverSelection()
        self.cell: tuple[int, int] | None = None
        self.key = self.target.key()
        self.current_mouse_cell: tuple[int, int] | None = None

        self.single_event_enabled = True
        self.multiple_event_enabled = True

    def update_state(self, new_state: CatscanState) -> None:
        self.state = new_state

    def update_stream_data(self, stream_data: EventStreamData) -> None:
        self.stream_data = stream_data

    def mouse_event(
        self,
        size: tuple[()] | tuple[int] | tuple[int, int],
        event: str,
        button: int,
        col: int,
        row: int,
        focus: bool,
    ) -> None:
        self.current_mouse_cell = (col, row)

    def data_view_for_hover(self, hover: HoverSelection) -> Any:
        return self.stream_data.transaction_events() if hover.within_transaction() else self.stream_data.events()

    def format_data(self, event: Event) -> dict[str, Any]:
        def strip_prefix(to_strip: str, to_compare: str) -> str:
            def prefix(s: str) -> str:
                return ".".join(s.split(".")[:-1])

            if prefix(to_strip) == prefix(to_compare):
                return to_strip.split(".")[-1]
            return to_strip

        def format_as_hex(item: tuple[str, Any]) -> tuple[str, Any]:
            name, value = item
            if self.hexargs_re.match(name):
                if isinstance(value, str):
                    return name, hex(int(value, base=0))
                return name, hex(value)
            return item

        display_data = dict(map(format_as_hex, event.data.items()))
        if self.state.sort_event_keys:
            display_data = dict(sorted(display_data.items()))
        return {strip_prefix(name, event.name): value for name, value in display_data.items()}

    def single_event_for_hover(self, hover: HoverSelection) -> Event | None:
        if hover.is_event():
            return hover.event

        it = self.data_view_for_hover(hover).get(hover.event_row)[hover.start_ps : hover.end_ps]
        event = next(it, None)
        if event is not None and next(it, None) is None:
            return event
        return None

    def enabled_for_target(self, hover: HoverSelection) -> bool:
        if not hover:
            return True
        if not self.single_event_enabled and not self.multiple_event_enabled:
            return False
        if self.single_event_for_hover(hover) is not None:
            return self.single_event_enabled
        return self.multiple_event_enabled

    def content(self) -> tuple[list[str], bool]:
        hover = self.target
        if not hover:
            return [], False

        if event := self.single_event_for_hover(hover):
            cycles = round(event.time // self.state.ps_per_cycle)
            lines = [
                f"time: {cycles:,} cyc",
            ]
            if not hover.abbrev_visible:
                lines.insert(0, f"abbrev: {event.abbrev}")
            if hover.within_transaction():
                lines.insert(0, f"name: {event.name}")
            lines.extend(f"{name}: {value}" for name, value in self.format_data(event).items())
            return lines, True

        histogram = summary_histogram(
            self.data_view_for_hover(hover).get(hover.event_row)[hover.start_ps : hover.end_ps]
        )
        total = histogram.total()
        return [f"{abbrev}: {count} ({count / total:.2%})" for abbrev, count in histogram.most_common(99)], True

    def lines(self) -> list[str]:
        lines, _bold_labels = self.content()
        return lines

    def position(self, width: int, height: int, size: tuple[int, int]) -> tuple[int, int]:
        assert self.cell is not None
        col, row = self.cell
        left = col + 2
        right_limit = size[0]
        if self.state.selection:
            right_limit = max(0, size[0] - self.get_sidebar_width() - 1)

        if left + width > right_limit:
            left = max(0, col - width - 1)
        if left + width > size[0]:
            left = max(0, size[0] - width)

        top = row + 1
        if top + height > size[1]:
            top = max(0, row - height - 1)
        return left, top

    def overlay(self, canvas: urwid.Canvas, size: tuple[int, int], focus: bool = False) -> urwid.CompositeCanvas:
        if not self.target or self.cell is None:
            return canvas

        lines, bold_labels = self.content()
        popup = HoverPopup(lines, bold_labels=bold_labels)
        width = min(popup.desired_width, size[0])
        height = min(popup.desired_height, size[1])
        left, top = self.position(width, height, size)

        canvas = urwid.CompositeCanvas(canvas)
        canvas.overlay(urwid.CompositeCanvas(popup.render((width, height), focus)), left=left, top=top)
        return canvas

    def on_hover(self, hover: HoverSelection) -> bool:
        if not self.enabled_for_target(hover):
            hover = HoverSelection()

        cell = self.current_mouse_cell
        key = hover.key(cell)
        if key == self.key:
            return False

        self.target = hover
        self.cell = cell if hover else None
        self.key = key
        self.invalidate()
        return True

    def clear(self) -> bool:
        return self.on_hover(HoverSelection())
