# Copyright (c) 2026 Ampere Computing. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause

# Assisted and/or generated by Codex:GPT-5

"""Focused event-row auto-pan decisions."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from catscan.commands import AutopanMode

if TYPE_CHECKING:
    from catscan.data import EventData
    from catscan.widgets.event_view import EventView


class Autopan:
    """Store auto-pan configuration and choose a horizontal target time."""

    def __init__(self, mode: AutopanMode, commit_event: str | None, commit_data_name: str | None) -> None:
        self.mode = mode
        self.commit_event = commit_event
        self.commit_data_name = commit_data_name

    @staticmethod
    def _row_has_visible_event(view: EventView, row: EventData) -> bool:
        start_ps, end_ps = view.visible_time_range()
        return end_ps > start_ps and any(row[start_ps:end_ps])

    @staticmethod
    def _last_event_start_time(view: EventView, event_time: int) -> int:
        visible_columns = max(0, view._columns - view.scrollable._border_width - view.state.column_header_width)
        return event_time - round((visible_columns - 1) * view.state.ps_per_char)

    @staticmethod
    def _nearest_event_is_after_viewport(view: EventView, row: EventData) -> bool:
        start_ps, end_ps = view.visible_time_range()
        older_event = row.closest_to(start_ps, direction="backwards")
        younger_event = row.closest_to(end_ps, direction="forwards")
        if older_event is not None and older_event.time >= start_ps:
            older_event = None
        if younger_event is not None and younger_event.time < end_ps:
            younger_event = None
        if older_event is None:
            return True
        if younger_event is None:
            return False
        return younger_event.time - end_ps <= start_ps - older_event.time

    def _commit_time(
        self,
        row: EventData,
        commit_syncer: Any | None,
        sync_index: int | None,
    ) -> int | None:
        commit_events = [
            event for event in row[:] if event.name == self.commit_event and self.commit_data_name in event.data
        ]
        if sync_index is not None:
            for event in commit_events:
                if event.data[self.commit_data_name] == sync_index:
                    return event.time
            return None

        if commit_syncer is None:
            return None

        for event in commit_events:
            if commit_syncer.other_has_sync_index(event.data[self.commit_data_name]):
                return event.time
        return None

    def target_time(
        self,
        view: EventView,
        row: EventData,
        *,
        commit_syncer: Any | None,
        sync_index: int | None = None,
    ) -> int | None:
        """Return a new viewport start time, or ``None`` when no pan is needed."""
        if self.mode == AutopanMode.NONE or self._row_has_visible_event(view, row):
            return None

        if self.mode == AutopanMode.COMMIT_EVENT:
            commit_time = self._commit_time(row, commit_syncer, sync_index)
            if commit_time is not None:
                return commit_time
        elif self.mode == AutopanMode.NEAREST_EVENT and not self._nearest_event_is_after_viewport(view, row):
            return self._last_event_start_time(view, row.last_time)

        return row.first_time
