# Copyright (c) 2026 Ampere Computing. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause

# Assisted and/or generated by Codex:GPT-5

"""Focused event-row auto-pan decisions."""

from __future__ import annotations

from collections.abc import Callable
from typing import TYPE_CHECKING, Any

from catscan.commands import AutopanMode

if TYPE_CHECKING:
    from catscan.data import Event, EventData
    from catscan.widgets.event_view import EventView


class Autopan:
    """Store auto-pan configuration and choose a horizontal target time."""

    def __init__(self, mode: AutopanMode, commit_event: str | None, commit_data_name: str | None) -> None:
        self.mode = mode
        self.commit_event = commit_event
        self.commit_data_name = commit_data_name

    @staticmethod
    def _row_has_visible_event(view: EventView, row: EventData) -> bool:
        start_ps, end_ps = view.visible_time_range()
        return end_ps > start_ps and any(row[start_ps:end_ps])

    @staticmethod
    def _last_event_start_time(view: EventView, event_time: int) -> int:
        visible_columns = view.visible_event_columns()
        return event_time - round((visible_columns - 1) * view.state.ps_per_char)

    @staticmethod
    def _nearest_offscreen_event(view: EventView, row: EventData) -> Event | None:
        start_ps, end_ps = view.visible_time_range()
        older_event = row.closest_to(start_ps, direction="backwards")
        younger_event = row.closest_to(end_ps, direction="forwards")
        if older_event is not None and older_event.time >= start_ps:
            older_event = None
        if younger_event is not None and younger_event.time < end_ps:
            younger_event = None
        if older_event is None:
            return younger_event
        if younger_event is None:
            return older_event
        if younger_event.time - end_ps <= start_ps - older_event.time:
            return younger_event
        return older_event

    def _event_time(
        self,
        row: EventData,
        event_name: str | None,
        predicate: Callable[[Event], bool] | None = None,
    ) -> int | None:
        """Return the first event time matching an event name and optional predicate."""
        for event in row[:]:
            if event.name == event_name and (predicate is None or predicate(event)):
                return event.time
        return None

    def _commit_time(
        self,
        row: EventData,
        commit_syncer: Any | None,
        sync_index: int | None,
    ) -> int | None:
        if self.commit_data_name is None:
            return None

        data_name = self.commit_data_name
        if sync_index is not None:
            return self._event_time(
                row,
                self.commit_event,
                lambda event: event.data.get(data_name) == sync_index,
            )

        if commit_syncer is None:
            return None

        return self._event_time(
            row,
            self.commit_event,
            lambda event: data_name in event.data and commit_syncer.other_has_sync_index(event.data[data_name]),
        )

    def target_time(
        self,
        view: EventView,
        row: EventData,
        *,
        commit_syncer: Any | None,
        sync_index: int | None = None,
    ) -> int | None:
        """Return a new viewport start time, or ``None`` when no pan is needed."""
        if self.mode == AutopanMode.NONE or self._row_has_visible_event(view, row):
            return None

        if self.mode == AutopanMode.COMMIT_EVENT:
            commit_time = self._commit_time(row, commit_syncer, sync_index)
            if commit_time is not None:
                return commit_time
        elif self.mode == AutopanMode.NEAREST_EVENT:
            nearest_event = self._nearest_offscreen_event(view, row)
            if nearest_event is not None:
                start_ps, _ = view.visible_time_range()
                if nearest_event.time < start_ps:
                    return self._last_event_start_time(view, nearest_event.time)
                return nearest_event.time

        return row.first_time
